# Generated by Django 3.2.6 on 2021-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_started_time',
            field=models.DateField(),
        ),
    ]
